# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pydart_api', [dirname(__file__)])
        except ImportError:
            import _pydart_api
            return _pydart_api
        if fp is not None:
            try:
                _mod = imp.load_module('_pydart_api', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pydart_api = swig_import_helper()
    del swig_import_helper
else:
    import _pydart_api
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def init():
  return _pydart_api.init()
init = _pydart_api.init

def destroy():
  return _pydart_api.destroy()
destroy = _pydart_api.destroy

def createWorld(*args):
  return _pydart_api.createWorld(*args)
createWorld = _pydart_api.createWorld

def createWorldFromSkel(*args):
  return _pydart_api.createWorldFromSkel(*args)
createWorldFromSkel = _pydart_api.createWorldFromSkel

def destroyWorld(*args):
  return _pydart_api.destroyWorld(*args)
destroyWorld = _pydart_api.destroyWorld

def saveWorldToFile(*args):
  return _pydart_api.saveWorldToFile(*args)
saveWorldToFile = _pydart_api.saveWorldToFile

def addSkeleton(*args):
  return _pydart_api.addSkeleton(*args)
addSkeleton = _pydart_api.addSkeleton

def numSkeletons(*args):
  return _pydart_api.numSkeletons(*args)
numSkeletons = _pydart_api.numSkeletons

def setSkeletonJointDamping(*args):
  return _pydart_api.setSkeletonJointDamping(*args)
setSkeletonJointDamping = _pydart_api.setSkeletonJointDamping

def resetWorld(*args):
  return _pydart_api.resetWorld(*args)
resetWorld = _pydart_api.resetWorld

def stepWorld(*args):
  return _pydart_api.stepWorld(*args)
stepWorld = _pydart_api.stepWorld

def render(*args):
  return _pydart_api.render(*args)
render = _pydart_api.render

def renderSkeleton(*args):
  return _pydart_api.renderSkeleton(*args)
renderSkeleton = _pydart_api.renderSkeleton

def renderSkeletonWithColor(*args):
  return _pydart_api.renderSkeletonWithColor(*args)
renderSkeletonWithColor = _pydart_api.renderSkeletonWithColor

def renderSkeletonMarkers(*args):
  return _pydart_api.renderSkeletonMarkers(*args)
renderSkeletonMarkers = _pydart_api.renderSkeletonMarkers

def getWorldTime(*args):
  return _pydart_api.getWorldTime(*args)
getWorldTime = _pydart_api.getWorldTime

def getWorldTimeStep(*args):
  return _pydart_api.getWorldTimeStep(*args)
getWorldTimeStep = _pydart_api.getWorldTimeStep

def setWorldTimeStep(*args):
  return _pydart_api.setWorldTimeStep(*args)
setWorldTimeStep = _pydart_api.setWorldTimeStep

def getWorldSimFrames(*args):
  return _pydart_api.getWorldSimFrames(*args)
getWorldSimFrames = _pydart_api.getWorldSimFrames

def setWorldSimFrame(*args):
  return _pydart_api.setWorldSimFrame(*args)
setWorldSimFrame = _pydart_api.setWorldSimFrame

def getWorldNumContacts(*args):
  return _pydart_api.getWorldNumContacts(*args)
getWorldNumContacts = _pydart_api.getWorldNumContacts

def getWorldContacts(*args):
  return _pydart_api.getWorldContacts(*args)
getWorldContacts = _pydart_api.getWorldContacts

def setWorldCollisionPair(*args):
  return _pydart_api.setWorldCollisionPair(*args)
setWorldCollisionPair = _pydart_api.setWorldCollisionPair

def getSkeletonName(*args):
  return _pydart_api.getSkeletonName(*args)
getSkeletonName = _pydart_api.getSkeletonName

def getSkeletonMass(*args):
  return _pydart_api.getSkeletonMass(*args)
getSkeletonMass = _pydart_api.getSkeletonMass

def getSkeletonNumBodies(*args):
  return _pydart_api.getSkeletonNumBodies(*args)
getSkeletonNumBodies = _pydart_api.getSkeletonNumBodies

def getSkeletonNumDofs(*args):
  return _pydart_api.getSkeletonNumDofs(*args)
getSkeletonNumDofs = _pydart_api.getSkeletonNumDofs

def getSkeletonNumJoints(*args):
  return _pydart_api.getSkeletonNumJoints(*args)
getSkeletonNumJoints = _pydart_api.getSkeletonNumJoints

def getSkeletonBodyName(*args):
  return _pydart_api.getSkeletonBodyName(*args)
getSkeletonBodyName = _pydart_api.getSkeletonBodyName

def getSkeletonDofName(*args):
  return _pydart_api.getSkeletonDofName(*args)
getSkeletonDofName = _pydart_api.getSkeletonDofName

def getSkeletonJointName(*args):
  return _pydart_api.getSkeletonJointName(*args)
getSkeletonJointName = _pydart_api.getSkeletonJointName

def getSkeletonMobile(*args):
  return _pydart_api.getSkeletonMobile(*args)
getSkeletonMobile = _pydart_api.getSkeletonMobile

def setSkeletonMobile(*args):
  return _pydart_api.setSkeletonMobile(*args)
setSkeletonMobile = _pydart_api.setSkeletonMobile

def setSkeletonSelfCollision(*args):
  return _pydart_api.setSkeletonSelfCollision(*args)
setSkeletonSelfCollision = _pydart_api.setSkeletonSelfCollision

def getSkeletonPositions(*args):
  return _pydart_api.getSkeletonPositions(*args)
getSkeletonPositions = _pydart_api.getSkeletonPositions

def getSkeletonVelocities(*args):
  return _pydart_api.getSkeletonVelocities(*args)
getSkeletonVelocities = _pydart_api.getSkeletonVelocities

def getSkeletonMassMatrix(*args):
  return _pydart_api.getSkeletonMassMatrix(*args)
getSkeletonMassMatrix = _pydart_api.getSkeletonMassMatrix

def getSkeletonCoriolisAndGravityForces(*args):
  return _pydart_api.getSkeletonCoriolisAndGravityForces(*args)
getSkeletonCoriolisAndGravityForces = _pydart_api.getSkeletonCoriolisAndGravityForces

def getSkeletonConstraintForces(*args):
  return _pydart_api.getSkeletonConstraintForces(*args)
getSkeletonConstraintForces = _pydart_api.getSkeletonConstraintForces

def setSkeletonPositions(*args):
  return _pydart_api.setSkeletonPositions(*args)
setSkeletonPositions = _pydart_api.setSkeletonPositions

def setSkeletonVelocities(*args):
  return _pydart_api.setSkeletonVelocities(*args)
setSkeletonVelocities = _pydart_api.setSkeletonVelocities

def setSkeletonForces(*args):
  return _pydart_api.setSkeletonForces(*args)
setSkeletonForces = _pydart_api.setSkeletonForces

def getSkeletonPositionLowerLimit(*args):
  return _pydart_api.getSkeletonPositionLowerLimit(*args)
getSkeletonPositionLowerLimit = _pydart_api.getSkeletonPositionLowerLimit

def getSkeletonPositionUpperLimit(*args):
  return _pydart_api.getSkeletonPositionUpperLimit(*args)
getSkeletonPositionUpperLimit = _pydart_api.getSkeletonPositionUpperLimit

def getSkeletonForceLowerLimit(*args):
  return _pydart_api.getSkeletonForceLowerLimit(*args)
getSkeletonForceLowerLimit = _pydart_api.getSkeletonForceLowerLimit

def getSkeletonForceUpperLimit(*args):
  return _pydart_api.getSkeletonForceUpperLimit(*args)
getSkeletonForceUpperLimit = _pydart_api.getSkeletonForceUpperLimit

def getSkeletonWorldCOM(*args):
  return _pydart_api.getSkeletonWorldCOM(*args)
getSkeletonWorldCOM = _pydart_api.getSkeletonWorldCOM

def getSkeletonWorldCOMVelocity(*args):
  return _pydart_api.getSkeletonWorldCOMVelocity(*args)
getSkeletonWorldCOMVelocity = _pydart_api.getSkeletonWorldCOMVelocity

def getBodyNodeMass(*args):
  return _pydart_api.getBodyNodeMass(*args)
getBodyNodeMass = _pydart_api.getBodyNodeMass

def getBodyNodeInertia(*args):
  return _pydart_api.getBodyNodeInertia(*args)
getBodyNodeInertia = _pydart_api.getBodyNodeInertia

def getBodyNodeShapeBoundingBoxDim(*args):
  return _pydart_api.getBodyNodeShapeBoundingBoxDim(*args)
getBodyNodeShapeBoundingBoxDim = _pydart_api.getBodyNodeShapeBoundingBoxDim

def getBodyNodeLocalCOM(*args):
  return _pydart_api.getBodyNodeLocalCOM(*args)
getBodyNodeLocalCOM = _pydart_api.getBodyNodeLocalCOM

def getBodyNodeWorldCOM(*args):
  return _pydart_api.getBodyNodeWorldCOM(*args)
getBodyNodeWorldCOM = _pydart_api.getBodyNodeWorldCOM

def getBodyNodeWorldCOMVelocity(*args):
  return _pydart_api.getBodyNodeWorldCOMVelocity(*args)
getBodyNodeWorldCOMVelocity = _pydart_api.getBodyNodeWorldCOMVelocity

def getBodyNodeWorldCOMSpatialVelocity(*args):
  return _pydart_api.getBodyNodeWorldCOMSpatialVelocity(*args)
getBodyNodeWorldCOMSpatialVelocity = _pydart_api.getBodyNodeWorldCOMSpatialVelocity

def getBodyNodeWorldCOMSpatialAcceleration(*args):
  return _pydart_api.getBodyNodeWorldCOMSpatialAcceleration(*args)
getBodyNodeWorldCOMSpatialAcceleration = _pydart_api.getBodyNodeWorldCOMSpatialAcceleration

def getBodyNodeLocalCOMSpatialVelocity(*args):
  return _pydart_api.getBodyNodeLocalCOMSpatialVelocity(*args)
getBodyNodeLocalCOMSpatialVelocity = _pydart_api.getBodyNodeLocalCOMSpatialVelocity

def getBodyNodeLocalCOMSpatialAcceleration(*args):
  return _pydart_api.getBodyNodeLocalCOMSpatialAcceleration(*args)
getBodyNodeLocalCOMSpatialAcceleration = _pydart_api.getBodyNodeLocalCOMSpatialAcceleration

def getBodyNodeNumContacts(*args):
  return _pydart_api.getBodyNodeNumContacts(*args)
getBodyNodeNumContacts = _pydart_api.getBodyNodeNumContacts

def getBodyNodeContacts(*args):
  return _pydart_api.getBodyNodeContacts(*args)
getBodyNodeContacts = _pydart_api.getBodyNodeContacts

def getBodyNodeTransformation(*args):
  return _pydart_api.getBodyNodeTransformation(*args)
getBodyNodeTransformation = _pydart_api.getBodyNodeTransformation

def getBodyNodeWorldLinearJacobian(*args):
  return _pydart_api.getBodyNodeWorldLinearJacobian(*args)
getBodyNodeWorldLinearJacobian = _pydart_api.getBodyNodeWorldLinearJacobian

def addBodyNodeExtForce(*args):
  return _pydart_api.addBodyNodeExtForce(*args)
addBodyNodeExtForce = _pydart_api.addBodyNodeExtForce

def addBodyNodeExtForceAt(*args):
  return _pydart_api.addBodyNodeExtForceAt(*args)
addBodyNodeExtForceAt = _pydart_api.addBodyNodeExtForceAt

def getJointTransform(*args):
  return _pydart_api.getJointTransform(*args)
getJointTransform = _pydart_api.getJointTransform

def getBodyNodeNumMarkers(*args):
  return _pydart_api.getBodyNodeNumMarkers(*args)
getBodyNodeNumMarkers = _pydart_api.getBodyNodeNumMarkers

def getMarkerPosition(*args):
  return _pydart_api.getMarkerPosition(*args)
getMarkerPosition = _pydart_api.getMarkerPosition

def readC3D(*args):
  return _pydart_api.readC3D(*args)
readC3D = _pydart_api.readC3D

def addAerodynamicForce(*args):
  return _pydart_api.addAerodynamicForce(*args)
addAerodynamicForce = _pydart_api.addAerodynamicForce
# This file is compatible with both classic and new-style classes.


